version: '2'
services:
  couchdb:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secret
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - couchdb_data:/bitnami/couchdb
      # - ./config:/opt/bitnami/couchdb/etc/local.d
volumes:
  couchdb_data:
    driver: local
