apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb
data:
  custom.ini: |
    [chttpd]
    authentication_handlers = {chttpd_auth, jwt_authentication_handler}, {chttpd_auth, proxy_authentication_handler}, {chttpd_auth, default_authentication_handler}
    require_valid_user_except_for_up = true

    [log]
    level = debug

    [couch_httpd_auth]
    proxy_use_secret = true
    secret = 92de07df7e7a3fe14808cef90a7cc0d91

    ; [jwt_keys]
    ; HS256:kid = 10083e2c-2c5b-4223-9221-304455ea661a
    ; HS256:_default = 10083e2c-2c5b-4223-9221-304455ea661a

    [httpd]
    ; proxy_use_secret=true
    ; secret=92de07df7e7a3fe14808cef90a7cc0d91
    enable_cors = true

    [admins]
    admin = -pbkdf2-a5c3244a0695ef4e47209755182325c92b41c045,c40c30a9ddaff2a5dbfbd312066d11d7,10

    [couchdb]
    uuid = 2ef03044f64b96272ed8a1f72c610226

    [log]
    level = debug

    [cors]
    origins = *
    headers = accept, authorization, content-type, origin, referer
    credentials = true
    methods = GET, PUT, POST, HEAD, DELETE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: couchdb
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - image: docker.io/bitnami/couchdb:3-debian-10
        name: couchdb
        volumeMounts:
          - name: data
            mountPath: //bitnami/couchdb
          - name: config
            mountPath: /opt/bitnami/couchdb/etc/local.d
      volumes:
      - name: config
        configMap:
          name: couchdb
          items:
            - key: custom.ini
              path: custom.ini
      - name: data
        persistentVolumeClaim:
          claimName: couchdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  selector:
    app: couchdb
  ports:
    - name: tcp
      protocol: TCP
      port: 5984
      targetPort: 5984